#!/usr/bin/env python3
"""Prepare convergence, relaxation, optics, and band VASP calculations."""

from __future__ import annotations

import argparse
import math
import shlex
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any

from workflow_common import (
    WorkflowError,
    copy_job,
    ensure_new_target,
    find_command,
    load_config,
    require_file,
    stage_settings,
    target_is_prepared,
)


def solphin_modules():
    try:
        from solphin import band_structure, vasp_inputs
    except (ImportError, ModuleNotFoundError) as exc:
        raise WorkflowError(
            "Solphin and its dependencies are not importable in this Python environment. "
            "Activate the environment in which Solphin, pymatgen, and sumo are installed. "
            f"Original error: {exc}"
        ) from exc
    return band_structure, vasp_inputs


def write_calculation(
    structure: Any,
    config: dict[str, Any],
    config_path: Path,
    stage: str,
    directory: Path,
    recipe: str | None = None,
    extra_incar: dict[str, Any] | None = None,
    allowed_existing: set[str] | None = None,
) -> None:
    _, vasp_inputs = solphin_modules()
    ensure_new_target(directory, allowed_existing)
    incar = stage_settings(config, stage)
    if extra_incar:
        incar.update(extra_incar)
    kwargs: dict[str, Any] = {"user_incar_settings": incar}
    if config.get("potcar_functional"):
        kwargs["potcar_functional"] = config["potcar_functional"]
    vasp_inputs.write_vasp_calculation(
        structure=structure,
        recipe=recipe or config["functional"],
        out_dir=str(directory),
        patches=config[stage].get("patches", []),
        **kwargs,
    )
    copy_job(config, config_path, [directory])


def write_gamma_kpoints(path: Path, mesh: list[int]) -> None:
    if len(mesh) != 3 or any(not isinstance(x, int) or x < 1 for x in mesh):
        raise WorkflowError("convergence.seed_kpoints must contain three positive integers.")
    path.write_text(
        "Automatic mesh for vaspup2.0\n0\nGamma\n"
        + " ".join(str(x) for x in mesh)
        + "\n0 0 0\n",
        encoding="utf-8",
    )


def shell_assignment(name: str, value: Any) -> str:
    return f"{name}={shlex.quote(str(value))}\n"


def prepare_convergence(
    structure: Any, config: dict[str, Any], config_path: Path, root: Path
) -> None:
    settings = config["convergence"]
    if not settings.get("enabled", True):
        print("SKIP convergence (disabled in config)")
        return
    directory = root / "convergence"
    input_dir = directory / "input"
    if target_is_prepared(input_dir) and (directory / "CONFIGURED").is_file():
        calculation_dirs = [input_dir]
        calculation_dirs.extend(sorted(path for path in (directory / "cutoff_converge").glob("*") if path.is_dir()))
        calculation_dirs.extend(sorted(path for path in (directory / "kpoint_converge").glob("*") if path.is_dir()))
        copy_job(config, config_path, calculation_dirs)
        print(f"SKIP convergence (already prepared): {directory}")
        return
    if not target_is_prepared(input_dir):
        ensure_new_target(input_dir)

        # KSPACING makes Solphin omit KPOINTS; vaspup needs an explicit file,
        # which is written immediately afterwards using the seed mesh.
        write_calculation(
            structure,
            config,
            config_path,
            "convergence",
            input_dir,
            recipe=settings["functional"],
            extra_incar={"ENCUT": config["encut"], "KSPACING": config["kspacing"]},
        )
        incar_path = input_dir / "INCAR"
        lines = [
            line
            for line in incar_path.read_text(encoding="utf-8").splitlines()
            if not line.startswith("KSPACING")
        ]
        incar_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
        write_gamma_kpoints(input_dir / "KPOINTS", settings["seed_kpoints"])

    encut = settings["encut"]
    meshes = settings["kpoints"]
    if not meshes or any(len(mesh) != 3 for mesh in meshes):
        raise WorkflowError("convergence.kpoints must be a non-empty list of 3-value meshes.")
    submit_cmd = settings.get("submit_cmd", "qsub")
    job_name_flag = settings.get("job_name_flag", "-N")
    text = "# Generated by solphin_automation; sourced by vaspup2.0.\n"
    text += shell_assignment("conv_encut", int(bool(encut.get("enabled", True))))
    text += shell_assignment("encut_start", int(encut["start"]))
    text += shell_assignment("encut_end", int(encut["stop"]))
    text += shell_assignment("encut_step", int(encut["step"]))
    text += shell_assignment("conv_kpoint", 1)
    text += shell_assignment("kpoints", ",".join(" ".join(map(str, mesh)) for mesh in meshes))
    text += shell_assignment("run_vasp", int(bool(settings.get("run_vasp", False))))
    text += shell_assignment("submit_cmd", submit_cmd)
    text += shell_assignment("job_name_flag", job_name_flag)
    text += shell_assignment("name", config["project_name"])
    (input_dir / "CONFIG").write_text(text, encoding="utf-8")

    if settings.get("run_vasp") and not (input_dir / config["scheduler"]["job_filename"]).is_file():
        raise WorkflowError("convergence.run_vasp is true, but no scheduler.job_template was supplied.")

    if settings.get("generate_directories", True):
        command = find_command(settings.get("command", "generate-converge"))
        completed = subprocess.run([command], cwd=directory, check=False)
        if completed.returncode:
            raise WorkflowError(f"{command} failed with exit status {completed.returncode}.")
    (directory / "CONFIGURED").write_text("Prepared by prepare_workflow.py\n", encoding="utf-8")
    print(f"READY convergence: {directory}")


def prepare_relax(structure: Any, config: dict[str, Any], config_path: Path, root: Path) -> None:
    directory = root / config["relax"]["directory"]
    if target_is_prepared(directory):
        copy_job(config, config_path, [directory])
        print(f"SKIP relax (already prepared): {directory}")
        return
    write_calculation(
        structure,
        config,
        config_path,
        "relax",
        directory,
        extra_incar={"KSPACING": config["kspacing"], "ENCUT": config["encut"]},
    )
    print(f"READY relax: {directory}")


def relaxed_structure(config: dict[str, Any], root: Path, vasp_inputs: Any):
    path = root / config["relax"]["directory"] / "CONTCAR"
    require_file(path, "relaxed structure (finish the relaxation calculation first)")
    return vasp_inputs.read_structure_pmg(str(path))


def prepare_optics(config: dict[str, Any], config_path: Path, root: Path) -> None:
    _, vasp_inputs = solphin_modules()
    directory = root / config["optics"]["directory"]
    if target_is_prepared(directory):
        copy_job(config, config_path, [directory])
        print(f"SKIP optics (already prepared): {directory}")
        return
    structure = relaxed_structure(config, root, vasp_inputs)
    write_calculation(
        structure,
        config,
        config_path,
        "optics",
        directory,
        extra_incar={"KSPACING": config["kspacing"], "ENCUT": config["encut"]},
    )
    print(f"READY optics: {directory}")


def prepare_bands(config: dict[str, Any], config_path: Path, root: Path) -> None:
    band_structure, vasp_inputs = solphin_modules()
    settings = config["bands"]
    directory = root / settings["directory"]
    if target_is_prepared(directory) or any(directory.glob("split-*/INCAR")):
        calc_dirs = sorted(path.parent for path in directory.glob("split-*/INCAR"))
        copy_job(config, config_path, calc_dirs or [directory])
        print(f"SKIP bands (already prepared): {directory}")
        return
    structure = relaxed_structure(config, root, vasp_inputs)
    functional = settings["functional"]
    hybrid = functional in {"PBE0", "HSE06", "DD_hybrid", "R2SCAN"}
    optics_dir = root / config["optics"]["directory"]
    scf_kpoints = require_file(optics_dir / "IBZKPT", "optics IBZKPT for hybrid bands") if hybrid else None
    scf_charge = None if hybrid else require_file(optics_dir / "CHGCAR", "optics CHGCAR for GGA bands")
    canonical, kpath = band_structure.generate_band_structure_path(
        structure=structure,
        definition=settings["path_definition"],
        density=int(settings["path_density"]),
    )
    directory.parent.mkdir(parents=True, exist_ok=True)
    splits = int(settings["splits"])
    kpoints, labels = kpath
    if splits > 1:
        make_folders = True
        kpts_per_split = math.ceil(len(kpoints) / splits)
    else:
        make_folders = False
        kpts_per_split = None

    if hybrid:
        from pymatgen.io.vasp.inputs import Kpoints

        ibzkpt = Kpoints.from_file(scf_kpoints)
    else:
        ibzkpt = None
    folders = band_structure._write_kpoint_files(
        directory=str(directory),
        kpoints=kpoints,
        labels=labels,
        make_folders=make_folders,
        ibzkpt=ibzkpt,
        kpts_per_split=kpts_per_split,
        cart_coords=False,
    )

    calc_dirs = []
    for folder in folders:
        calc_dir = directory / folder
        incar = {"KSPACING": 0, "ENCUT": config["encut"]}
        if not hybrid:
            incar["ICHARG"] = 11
        write_calculation(
            canonical,
            config,
            config_path,
            "bands",
            calc_dir,
            recipe=functional,
            extra_incar=incar,
            allowed_existing={"KPOINTS"},
        )
        if scf_charge:
            shutil.copy2(scf_charge, calc_dir / "CHGCAR")
        calc_dirs.append(calc_dir)
    print(f"READY bands ({len(calc_dirs)} calculation(s)): {directory}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("structure", help="starting POSCAR, CIF, or other pymatgen structure file")
    parser.add_argument("config", help="workflow config.json")
    parser.add_argument(
        "--stage",
        choices=("auto", "convergence", "relax", "optics", "bands"),
        default="auto",
        help="stage to prepare; auto prepares every stage whose prerequisites exist",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    try:
        config, config_path, root = load_config(args.config)
        root.mkdir(parents=True, exist_ok=True)
        structure_path = require_file(Path(args.structure).expanduser().resolve(), "starting structure")
        _, vasp_inputs = solphin_modules()
        structure = vasp_inputs.read_structure_pmg(str(structure_path))

        if args.stage == "convergence":
            prepare_convergence(structure, config, config_path, root)
        elif args.stage == "relax":
            prepare_relax(structure, config, config_path, root)
        elif args.stage == "optics":
            prepare_optics(config, config_path, root)
        elif args.stage == "bands":
            prepare_bands(config, config_path, root)
        else:
            prepare_convergence(structure, config, config_path, root)
            if config["convergence"].get("enabled", True) and not config["convergence"].get(
                "parameters_confirmed", False
            ):
                print(
                    "WAIT relax: analyse convergence, update encut/kspacing in config.json, "
                    "then set convergence.parameters_confirmed to true"
                )
                return 0
            prepare_relax(structure, config, config_path, root)
            try:
                prepare_optics(config, config_path, root)
            except WorkflowError as exc:
                print(f"WAIT optics: {exc}")
            try:
                prepare_bands(config, config_path, root)
            except WorkflowError as exc:
                print(f"WAIT bands: {exc}")
        return 0
    except WorkflowError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
